### ISSUE TITLE
Enable arithmetic expressions for the metrics loaded by the tool

### ISSUE THREAD

**Issue by hdmsantander** [hdmsantander/archinaut#3]
Currently we have the metrics section of the *archinaut.yml* file as follows:

```YAML
metrics:
  - name: 'Location'
    filename: true
  - name: 'Lines'
    rename: 'SCC_LOC'
  - name: 'Code'
    rename: 'SCC_CLOC'
  - name: 'Complexity'
    rename: 'SCC_COMPLEXITY'
```

The idea is to have a way to express new metrics based on other metrics loaded by the tool. Like for example:

* `AWESOME_METRIC = SCC_LOC * SCC_CLOC`
* `MINDBLOWING_METRIC = AWESOME_METRIC / SCC_COMPLEXITY`

The following operations are needed:
* addition
* substraction
* division
* multiplication
