### ISSUE TITLE
Find a way to incorporate depends metrics and relationships into archinaut

### ISSUE THREAD

**Issue by hdmsantander** [hdmsantander/archinaut#4]
Currently the [depends](https://github.com/multilang-depends/depends) metrics loaded by archinaut are not used in the metrics report or in the threshold violations report. Even though there's a section of the configuration file dedicated to the metrics and the contents of the file are parsed and loaded in memory.

Currently the section of the configuration file that loads the depends metrics looks as follows:

```YAML
file: 'depends.json'
format: 'DEPENDS'
renaming:
  pathSeparator: '.'
  prefix: 'main.java.'
  suffix: ''
  substitutions:
    - order: 1
      substitute: '.'
      with: '_'
metrics:
  - name: 'Call'
  - name: 'Import'
  - name: 'Return'
  - name: 'Use'
  - name: 'Parameter'
  - name: 'Contain'
  - name: 'Implement'
  - name: 'Create'
  - name: 'Extend'
```

Find a way to integrate the depends metrics and modularity violations that could result from them into the JUnit report generated by archinaut.
